server:
  port: 9001
  servlet:
    context-path: /teatour
  tomcat:
    uri-encoding: UTF-8
swagger:
  enable: true
  title: 接口文档

knife4j:
  enable: true

spring:
  application:
    name: teatour
  #  jackson:
  #    serialization:
  #      write-dates-as-timestamps: true
  #    date-format: yyyy-MM-dd HH:mm:ss
  #    time-zone: GMT+8
  #    defaultPropertyInclusion: non_null #非空属性才序列化
  #    deserialization:
  #      FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化，重要！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost :3306/teatour?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    druid:
      connection-init-sqls: set names utf8mb4
      initial-size: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      min-idle: 5
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    excluded-view-names:
##    mode: jsp
#    prefix: classpath:/templates/
#    suffix: .jsp
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      #页面默认后缀目录
      suffix: .jsp

  web:
    resources:
      static-locations:
        classpath: /

##上传的绝对路径
#file:
#  upload:
#    path: C://Users/Administrator/teatour/src/main/resources/static/img/newProd/     #最关键#
#      relative: /newProd/**
#file:
#  upload:
#    path:
#      relative: /newProd/**

  servlet:
    multipart:
      max-file-size: 5MB

#  redis:
#    host: 192.168.52.113
#    database: 1
#    lettuce:
#      pool:
#        max-active: 1000
#        max-idle: 8
#        max-wait: -1
#        min-idle: 10
#    password: ''
#    port: 6379
#    timeout: 10000ms
#
#  rabbitmq:
#    host: 192.168.99.100
#    virtual-host: /
#    port: 5672
#    # 生产端确认回调
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.practice.seckill.common.entity
#  #  global-config:
#  #    db-config:
#  #      id-type: auto #id生成规则：数据库id自增
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


